exit on error

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+# exit on error
+set -e
+
 EXE="./target/debug/ece461_team19_cli"
 
 if [ -x "$(command -v rustup)" ]; then
